services:
  - type: web
    name: myapp-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    github:
      repo: justcausee/to-do-list
      branch: main

  - type: web
    name: myapp-backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/to-do-list
    github:
      repo: justcausee/to-do-list
      branch: main
